name: release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: prep
        run: |
          echo ::set-output name=tags::ghcr.io/eastwd/jenkins-lint:${GITHUB_REF#refs/tags/v}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PATOEKN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/eastwd/jenkins-lint:latest, ${{ steps.prep.outputs.tags }}
          push: true
        env:
          DOCKER_BUILDKIT: 1
