name: test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test ./jenkins -coverprofile=coverage.txt -covermode=atomic

    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
